Downgrade proto library to fix build error (#14)
https://github.com/protocolbuffers/protobuf/issues/9688 caused build
errors when trying to integrate the latest `pyprotoc-plugin` changes
into https://github.com/3rdparty/eventuals.

Fixes build errors of the form:
```
ERROR: /home/vscode/.cache/dazel/tests/external/com_envoyproxy_protoc_gen_validate/validate/BUILD:28:17: Label '@com_google_protobuf//:protobuf_python' is duplicated in the 'deps' attribute of rule 'validate_py'
ERROR: /home/vscode/.cache/dazel/tests/external/envoy_api/envoy/extensions/filters/network/http_connection_manager/v3/BUILD:7:18: Target '@com_envoyproxy_protoc_gen_validate//validate:validate_proto' contains an error and its package is in error and referenced by '@envoy_api//envoy/extensions/filters/network/http_connection_manager/v3:pkg'
INFO: Repository com_github_curl_curl instantiated at:
  /workspaces/respect/submodules/eventuals/WORKSPACE.bazel:26:5: in <toplevel>
  /workspaces/respect/submodules/eventuals/bazel/deps.bzl:24:14: in deps
  /home/vscode/.cache/dazel/tests/external/com_github_3rdparty_bazel_rules_curl/bazel/deps.bzl:30:10: in deps
  /home/vscode/.cache/dazel/tests/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /home/vscode/.cache/dazel/tests/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
ERROR: Analysis of target '//test:death-client' failed; build aborted:
```